<?php

use function PHPSTORM_META\map;

return [
    // Code Execution Functions
    'call_user_func',
    'call_user_func_array',
    'create_function',
    'eval',
    'include',
    'include_once',
    'require',
    'require_once',
    // System Functions
    'exec',
    'getenv',
    'passthru',
    'pcntl_exec',
    'pcntl_fork',
    'pcntl_signal',
    'popen',
    'proc_close',
    'proc_get_status',
    'proc_nice',
    'proc_open',
    'proc_terminate',
    'putenv',
    'shell_exec',
    'system',
    // Network Functions
    'curl_exec',
    'curl_multi_exec',
    'dns_get_record',
    'fsockopen',
    'gethostbyname',
    'mail',
    'pfsockopen',
    'socket_connect',
    'socket_create',
    // File System Functions
    'basename',
    'chgrp',
    'chmod',
    'chown',
    'copy',
    'dirname',
    'fclose',
    'file',
    'file_get_contents',
    'file_put_contents',
    'fopen',
    'fread',
    'fwrite',
    'glob',
    'highlight_file',
    'link',
    'mkdir',
    'opendir',
    'parse_ini_file',
    'pathinfo',
    'readdir',
    'readfile',
    'realpath',
    'rename',
    'rmdir',
    'scandir',
    'show_source',
    'symlink',
    'tempnam',
    'tmpfile',
    'touch',
    'unlink',
    // Reflection Functions
    'class_exists',
    'method_exists',
    'property_exists',
    'function_exists',
    'get_class',
    'get_class_methods',
    'get_class_vars',
    'get_object_vars',
    'get_defined_functions',
    'get_defined_vars',
    'get_defined_constants',
    // Output Functions
    'debug_backtrace',
    'debug_print_backtrace',
    'echo',
    'header',
    'ob_end_flush',
    'ob_get_contents',
    'ob_start',
    'phpinfo',
    'print',
    'print_r',
    'printf',
    'setcookie',
    'setrawcookie',
    'var_dump',
    'var_export',
    // Error/Exception Functions
    'die',
    'error_reporting',
    'exit',
    'set_error_handler',
    'set_exception_handler',
    'trigger_error',
    'user_error',
    // Session Functions
    'session_start',
    'session_destroy',
    'session_write_close',
    'session_regenerate_id',
    // Database Functions
    'mysql_connect',
    'mysqli_connect',
    'pg_connect',
    'sqlite_open',
    // Stream Functions
    'stream_context_create',
    'stream_socket_client',
    'stream_socket_server',
    'stream_wrapper_register',
    // Miscellaneous Functions
    'base64_decode',
    'sleep',
    'time_nanosleep',
    'usleep',
    'unserialize',
];